trigger:
- dev
pool: 
  name: cloudresumebiceps
  vmImage: ubuntu-latest
  
jobs:
- job: testjob
  displayName: 'simple test job'
  steps: 
  - script: echo "hello from self-hosted agent" && whoami && pwd 